import type { Metadata } from "next";
import { Nunito, Nunito_Sans, Comfortaa, Prompt } from "next/font/google";
import "./globals.scss";
import NavBar from "./components/navBar/navBar";
import Logo from "./components/Logo/logo";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ['latin'],
});

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ['latin'],
});

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});

const prompt = Prompt({
  variable: "--font-prompt",
  subsets: ["latin"],
  weight: '400',
});

export const metadata: Metadata = {
  title: "SoundDrop Music",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en,ru">
      <body className={`${comfortaa.variable} ${nunito.variable} ${nunitoSans.variable} ${prompt.variable}`}>
        <div className="nav_container">
          <Logo />
          <NavBar />
        </div>
        <main>
          <div className='container'>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
