import type { Metadata } from "next";
import { Nunito, Nunito_Sans, Comfortaa, Prompt } from "next/font/google";
import "./styles/globals.scss";
import Providers from "@/components/Providers";
import NavBar from "../components/Navigation/Navigation";
import Logo from "../components/Logo/logo";

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ['latin'],
});

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito-sans",
  subsets: ['latin'],
});

const comfortaa = Comfortaa({
  variable: "--font-comfortaa",
  subsets: ["latin"],
});

const prompt = Prompt({
  variable: "--font-prompt",
  subsets: ["latin"],
  weight: '400',
});

export const metadata: Metadata = {
  title: "SoundDrop Music",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en,ru">
      <body className={`${comfortaa.variable} ${nunito.variable} ${nunitoSans.variable} ${prompt.variable}`}>
        <Providers>
          <header className="navigation">
            <Logo />
            <NavBar />
          </header>
          <main>
            <div className="container">
              {children}
            </div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
